blueprint:
  name: Smart Motion-Controlled Lighting
  description: >-
    Automatic lighting with motion detection, configurable auto-off timer,  
    and safety backup checks. Includes periodic monitoring and failure notifications.
    Supports multiple motion sensors and manual override functionality.
  domain: automation
  input:
    motion_sensors:
      name: Motion Sensors
      description: Motion sensors to trigger the automation (can select multiple)
      selector:
        target:
          entity:
            domain: binary_sensor
            device_class: motion
    light_entities:
      name: Lights
      description: Lights to control (can select multiple)
      selector:
        target:
          entity:
            domain: light
    timer_entity:
      name: Timer
      description: Timer helper for auto-off functionality
      selector:
        entity:
          domain: timer
    auto_off_duration:
      name: Auto-off Duration
      description: Time to wait before turning off the lights after motion stops
      default: "00:02:00"
      selector:
        duration:
    manual_override_entity:
      name: Manual Override Switch
      description: Switch to temporarily disable auto-off functionality
      default: ""
      selector:
        entity:
          domain: switch
    manual_override_duration:
      name: Manual Override Duration
      description: How long to keep manual override active (0 = until manually disabled)
      default: "00:30:00"
      selector:
        duration:
    periodic_check_minutes:
      name: Periodic Check Interval
      description: Minutes between periodic safety checks
      default: 30
      selector:
        number:
          min: 5
          max: 120
          unit_of_measurement: minutes
    enable_notifications:
      name: Enable Notifications
      description: Enable error notifications
      default: false
      selector:
        boolean:
    notification_target:
      name: Notification Target
      description: Target for notifications (mobile app, persistent notification, etc.)
      default: ""
      selector:
        target:
    notification_title:
      name: Notification Title
      description: Title for error notifications
      default: "Light Control Error!"
      selector:
        text:
    notification_message:
      name: Notification Message
      description: Message for error notifications
      default: "Lights could not be turned off correctly on first attempt!"
      selector:
        text:

alias: "{{ blueprint.name }}"
description: "{{ blueprint.description }}"

triggers:
  - entity_id: !input motion_sensors
    id: motion_detected
    trigger: state
    to: "on"
  - entity_id: !input motion_sensors
    id: motion_clear
    trigger: state
    to: "off"
  - trigger: state
    entity_id: !input light_entities
    to: "on"
    id: light_on
  - entity_id: !input timer_entity
    id: timer_finished
    trigger: state
    to: idle
    from: active
  - minutes: "{{ periodic_check_minutes }}"
    id: periodic_check
    trigger: time_pattern
  - entity_id: !input manual_override_entity
    id: manual_override_on
    trigger: state
    to: "on"
  - entity_id: !input manual_override_entity
    id: manual_override_off
    trigger: state
    to: "off"

actions:
  - choose:
      - conditions:
          - condition: trigger
            id: motion_detected
          - condition: template
            value_template: >-
              {% set lights_off = namespace(count=0) %}
              {% for entity_id in light_entities %}
                {% if states(entity_id) == 'off' %}
                  {% set lights_off.count = lights_off.count + 1 %}
                {% endif %}
              {% endfor %}
              {{ lights_off.count > 0 }}
        sequence:
          - target: !input light_entities
            action: light.turn_on
            data: {}
          - action: timer.cancel
            target:
              entity_id: !input timer_entity

      - conditions:
          - condition: trigger
            id:
              - motion_clear
              - light_on
              - periodic_check
          - condition: template
            value_template: >-
              {% set lights_on = namespace(count=0) %}
              {% for entity_id in light_entities %}
                {% if states(entity_id) == 'on' %}
                  {% set lights_on.count = lights_on.count + 1 %}
                {% endif %}
              {% endfor %}
              {{ lights_on.count > 0 }}
          - condition: template
            value_template: >-
              {% set any_motion = false %}
              {% for entity_id in motion_sensors %}
                {% if states(entity_id) == 'on' %}
                  {% set any_motion = true %}
                {% endif %}
              {% endfor %}
              {{ not any_motion }}
          - condition: template
            value_template: >-
              {% if manual_override_entity != '' %}
                {{ states(manual_override_entity) == 'off' }}
              {% else %}
                {{ true }}
              {% endif %}
        sequence:
          - action: timer.start
            data:
              duration: !input auto_off_duration
            target:
              entity_id: !input timer_entity

      - conditions:
          - condition: trigger
            id: timer_finished
        sequence:
          - condition: template
            value_template: >-
              {% set any_motion = false %}
              {% for entity_id in motion_sensors %}
                {% if states(entity_id) == 'on' %}
                  {% set any_motion = true %}
                {% endif %}
              {% endfor %}
              {{ not any_motion }}
          - condition: template
            value_template: >-
              {% set lights_on = namespace(count=0) %}
              {% for entity_id in light_entities %}
                {% if states(entity_id) == 'on' %}
                  {% set lights_on.count = lights_on.count + 1 %}
                {% endif %}
              {% endfor %}
              {{ lights_on.count > 0 }}
          - condition: template
            value_template: >-
              {% if manual_override_entity != '' %}
                {{ states(manual_override_entity) == 'off' }}
              {% else %}
                {{ true }}
              {% endif %}
          - target: !input light_entities
            action: light.turn_off
            data: {}
          - delay:
              seconds: 2
          - condition: template
            value_template: >-
              {% set lights_still_on = namespace(count=0) %}
              {% for entity_id in light_entities %}
                {% if states(entity_id) == 'on' %}
                  {% set lights_still_on.count = lights_still_on.count + 1 %}
                {% endif %}
              {% endfor %}
              {{ lights_still_on.count > 0 }}
          - if:
              - condition: template
                value_template: "{{ enable_notifications }}"
            then:
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ notification_target != '' }}"
                    sequence:
                      - service: notify.mobile_app
                        target: !input notification_target
                        data:
                          title: !input notification_title
                          message: !input notification_message
                          data:
                            priority: high
                            channel: alerts
                  - conditions:
                      - condition: template
                        value_template: "{{ notification_target == '' }}"
                    sequence:
                      - service: persistent_notification.create
                        data:
                          title: !input notification_title
                          message: !input notification_message
                          notification_id: "light_control_error_{{ now().timestamp() }}"

      - conditions:
          - condition: trigger
            id: manual_override_on
        sequence:
          - action: timer.cancel
            target:
              entity_id: !input timer_entity
          - if:
              - condition: template
                value_template: "{{ manual_override_duration != '00:00:00' }}"
            then:
              - delay:
                  seconds: "{{ manual_override_duration.split(':') | map('int') | list | sum }}"
              - condition: template
                value_template: "{{ states(manual_override_entity) == 'on' }}"
              - service: switch.turn_off
                target:
                  entity_id: !input manual_override_entity

      - conditions:
          - condition: trigger
            id: manual_override_off
        sequence:
          - condition: template
            value_template: >-
              {% set any_motion = false %}
              {% for entity_id in motion_sensors %}
                {% if states(entity_id) == 'on' %}
                  {% set any_motion = true %}
                {% endif %}
              {% endfor %}
              {{ not any_motion }}
          - condition: template
            value_template: >-
              {% set lights_on = namespace(count=0) %}
              {% for entity_id in light_entities %}
                {% if states(entity_id) == 'on' %}
                  {% set lights_on.count = lights_on.count + 1 %}
                {% endif %}
              {% endfor %}
              {{ lights_on.count > 0 }}
          - action: timer.start
            data:
              duration: !input auto_off_duration
            target:
              entity_id: !input timer_entity

mode: restart
max_exceeded: silent
