blueprint:
  name: Smart Motion-Controlled Lighting
  description: >-
    Automatic lighting with motion detection, configurable auto-off timer,  
    and safety backup checks. Includes periodic monitoring and failure notifications.
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      description: Motion sensor to trigger the automation
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_entities:
      name: Lights
      description: Lights to control (can select multiple)
      selector:
        target:
          entity:
            domain: light
    timer_entity:
      name: Timer
      description: Timer helper for auto-off functionality
      selector:
        entity:
          domain: timer
    auto_off_duration:
      name: Auto-off Duration
      description: Time to wait before turning off the lights after motion stops
      default: "00:02:00"
      selector:
        duration:
    periodic_check_minutes:
      name: Periodic Check Interval
      description: Minutes between periodic safety checks
      default: 30
      selector:
        number:
          min: 5
          max: 120
          unit_of_measurement: minutes
    enable_notifications:
      name: Enable Notifications
      description: Enable error notifications
      default: false
      selector:
        boolean:
    notification_target:
      name: Notification Target
      description: Target for notifications (mobile app, persistent notification, etc.)
      default: ""
      selector:
        target:
    notification_title:
      name: Notification Title
      description: Title for error notifications
      default: "Light Control Error!"
      selector:
        text:
    notification_message:
      name: Notification Message
      description: Message for error notifications
      default: "Lights could not be turned off correctly on first attempt!"
      selector:
        text:

alias: "{{ blueprint.name }}"
description: "{{ blueprint.description }}"

triggers:
  - entity_id: !input motion_sensor
    id: motion_detected
    trigger: state
    to: "on"
  - entity_id: !input motion_sensor
    id: motion_clear
    trigger: state
    to: "off"
  - trigger: state
    entity_id: !input light_entities
    to: "on"
    id: light_on
  - entity_id: !input timer_entity
    id: timer_finished
    trigger: state
    to: idle
    from: active
  - minutes: "{{ periodic_check_minutes }}"
    id: periodic_check
    trigger: time_pattern

actions:
  - choose:
      - conditions:
          - condition: trigger
            id: motion_detected
          - condition: template
            value_template: >-
              {% set lights_off = namespace(count=0) %}
              {% for entity_id in light_entities %}
                {% if states(entity_id) == 'off' %}
                  {% set lights_off.count = lights_off.count + 1 %}
                {% endif %}
              {% endfor %}
              {{ lights_off.count > 0 }}
        sequence:
          - target: !input light_entities
            action: light.turn_on
            data: {}
          - action: timer.cancel
            target:
              entity_id: !input timer_entity

      - conditions:
          - condition: trigger
            id:
              - motion_clear
              - light_on
              - periodic_check
          - condition: template
            value_template: >-
              {% set lights_on = namespace(count=0) %}
              {% for entity_id in light_entities %}
                {% if states(entity_id) == 'on' %}
                  {% set lights_on.count = lights_on.count + 1 %}
                {% endif %}
              {% endfor %}
              {{ lights_on.count > 0 }}
          - condition: state
            entity_id: !input motion_sensor
            state: "off"
        sequence:
          - action: timer.start
            data:
              duration: !input auto_off_duration
            target:
              entity_id: !input timer_entity

      - conditions:
          - condition: trigger
            id: timer_finished
        sequence:
          - condition: state
            entity_id: !input motion_sensor
            state: "off"
          - condition: template
            value_template: >-
              {% set lights_on = namespace(count=0) %}
              {% for entity_id in light_entities %}
                {% if states(entity_id) == 'on' %}
                  {% set lights_on.count = lights_on.count + 1 %}
                {% endif %}
              {% endfor %}
              {{ lights_on.count > 0 }}
          - target: !input light_entities
            action: light.turn_off
            data: {}
          - delay:
              seconds: 2
          - condition: template
            value_template: >-
              {% set lights_still_on = namespace(count=0) %}
              {% for entity_id in light_entities %}
                {% if states(entity_id) == 'on' %}
                  {% set lights_still_on.count = lights_still_on.count + 1 %}
                {% endif %}
              {% endfor %}
              {{ lights_still_on.count > 0 }}
          - if:
              - condition: template
                value_template: "{{ enable_notifications }}"
            then:
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ notification_target != '' }}"
                    sequence:
                      - service: notify.mobile_app
                        target: !input notification_target
                        data:
                          title: !input notification_title
                          message: !input notification_message
                          data:
                            priority: high
                            channel: alerts
                  - conditions:
                      - condition: template
                        value_template: "{{ notification_target == '' }}"
                    sequence:
                      - service: persistent_notification.create
                        data:
                          title: !input notification_title
                          message: !input notification_message
                          notification_id: "light_control_error_{{ now().timestamp() }}"

mode: restart
max_exceeded: silent
